### ISSUE TITLE
关于时序图的排版的一个问题

### ISSUE THREAD

**Issue by XSun771** [huhai463127310/webchart#10]
首先感谢作者的辛苦工作，提供了一个这么优秀有用的软件！

```
Note left of x:检测到链路xz的费用升高的节点
Note right of y:被x通知其距离向量发生变化的x的邻居节点
x->x:根据变更的c(x,z)与\n内部保存的邻居通告的距离向量\n更新自己的距离向量.\n
x->y:通知自己的距离向量要更新.
```
这个的时序图，会发现`根据变更的c(x,z)与\n内部保存的邻居通告的距离向量\n更新自己的距离向量.\n`与`通知自己的距离向量要更新.`的位置特别近，几乎要叠在一起了，不知能否再优化一下？另外`通知自己的距离向量要更新.`这种比较长的描述出现时，会发现并不能出现在x->x这个自己指向自己的线的中间，似乎也有优化的空间？

谢谢

**Comment by sdtime-io** [comment]
http://sizhuiit.com:9989/static/
升级版
